-- PL/SQL의 틀
DECLARE 
-- 변수선언
BEGIN
-- 실행부
END;
/

-------------------------------------------------------------------

-- 1) HELLO WORLD 출력하기
DECLARE 
-- 변수선언
BEGIN
-- 실행부
    DBMS_OUTPUT.PUT_LINE('HELLO WORLD');
END;
/


-- 2) 변수 선언 후 출력하기
DECLARE 
-- 변수선언
    USERNAME VARCHAR2(5);
    USERAGE NUMBER(3);
    USERADDR VARCHAR2(20) := '서울시 서초구';
BEGIN
-- 실행부
    USERAGE := 24;
    DBMS_OUTPUT.PUT_LINE(USERAGE);
    DBMS_OUTPUT.PUT_LINE('USERADDR = ' || USERADDR);
END;
/


-- 3) DB에서 추출한 후 출력
SELECT EMPLOYEE_ID, FIRST_NAME
INTO EMPNO, EMPNAME
FROM EMPLOYEES
WHERE FIRST_NAME='Susan';
-------------------------------
DECLARE
    EMPNO EMPLOYEES.EMPLOYEE_ID%TYPE;
    EMPNAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN
    DBMS_OUTPUT.PUT_LINE('사번 / 이름');
    DBMS_OUTPUT.PUT_LINE('------------');
    SELECT EMPLOYEE_ID, FIRST_NAME
    INTO EMPNO, EMPNAME
    FROM EMPLOYEES
    WHERE FIRST_NAME='Susan';
    DBMS_OUTPUT.PUT_LINE(EMPNO || ' / ' || EMPNAME);
END;
/


-- 4) DB에서 추출한 후 출력(여러줄)
DECLARE
    TYPE FIRST_NAME_TABLE_TYPE IS TABLE OF EMPLOYEES.FIRST_NAME%YPE
    INDEX BY BINARY INTEGER;
    TYPE JOB_ID_TABLE_TYPE IS TABLE OF EMPLOYEES.JOB_ID%TYPE
    INDEX BY BINARY_INTEGER;
    TYPE EMPLOYEE_ID_TABLE_TYPE IS TABLE OF EMPLOYEES.EMPLOYEE_ID%TYPE
    INDEX BY BINARY_INTEGER;
    
    NAME TABLE FIRST_NAME_TABLE_TYPE;
    JOB_TABLE JOB_ID_TABLE_TYPE;
    EMPNO_TABLE EMPLOYEE_ID_TABLE_TYPE;
    I BINARY_INTEGER := 0;
BEGIN
END;

/