---- 테이블 만들기 
--CREATE TABLE GRADE (
--    STUNUM NUMBER(4)PRIMARY KEY,
--    STUNAME VARCHAR2(20) NOT NULL, 
--    KOR NUMBER(4) NOT NULL,
--    ENG NUMBER(4) NOT NULL,
--    MATH NUMBER(4) NOT NULL,
--    SUM NUMBER(4),
--    AVG NUMBER(5, 1),
--    RANK NUMBER(4)
--); 
--
---- 시퀀스 위한 테이블 복사
---- CREATE TABLE COPY_GRADE
---- AS 
---- SELECT *
---- FROM GRADE WHERE 1=0;
--
--DROP TABLE SEQ_GRADE;
---- 시퀀스 만들기
--CREATE SEQUENCE SEQ_GRADE 
--START WITH 1
--INCREMENT BY 1;
--

DROP TABLE SCORE;
--점수테이블 생성
CREATE TABLE SCORE (
    HAKBUN NUMBER(4),
    HAKNAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4) NOT NULL,
    ENG NUMBER(4) NOT NULL,
    MAT NUMBER(4) NOT NULL,
    TOT NUMBER(4) DEFAULT 0,
    AVE NUMBER(5,1) DEFAULT 0,
    RANK NUMBER(4)
);
ALTER TABLE SCORE ADD CONSTRAINT SCORE_PK PRIMARY KEY(HAKBUN);


--프로시저 생성
CREATE OR REPLACE PROCEDURE SCORE_PROC(
    S_HAKBUN SCORE.HAKBUN%TYPE,
    S_HAKNAME SCORE.HAKNAME%TYPE,
    S_KOR SCORE.KOR%TYPE,
    S_ENG SCORE.ENG%TYPE,
    S_MAT SCORE.MAT%TYPE
)
IS
    S_TOT SCORE.TOT%TYPE;
    S_AVE SCORE.AVE%TYPE;
BEGIN
    S_TOT := S_KOR + S_ENG + S_MAT;
    S_AVE := (S_KOR + S_ENG + S_MAT) / 3;
​
    INSERT INTO SCORE(HAKBUN, HAKNAME, KOR, ENG, MAT, TOT, AVE) 
    VALUES(S_HAKBUN, S_HAKNAME, S_KOR, S_ENG, S_MAT, S_TOT, S_AVE);
END;
/

--랭크적용 프로시저
CREATE OR REPLACE PROCEDURE SCORE_RANK_PROC
IS
    S_RANK SCORE.RANK%TYPE;
    SCORE_ROW SCORE%ROWTYPE;
BEGIN
    UPDATE SCORE SET RANK = (SELECT S_RANK FROM(SELECT HAKBUN, RANK() OVER(ORDER BY TOT DESC) AS S_RANK FROM SCORE))
    WHERE SCORE.HAKBUN = HAKBUN;
END;
/
SELECT S_RANK FROM(SELECT HAKBUN, RANK() OVER(ORDER BY TOT DESC) AS S_RANK FROM SCORE);

--트리거 적용
CREATE OR REPLACE TRIGGER SCORE_INPUT
    AFTER INSERT ON SCORE
BEGIN
    UPDATE SCORE SET TOT = (KOR+ENG+MAT);
    UPDATE SCORE SET AVE = (KOR+ENG+MAT)/3;
END;
/

EXECUTE SCORE_PROC(1,'홍길동',99,80,85); 
EXECUTE SCORE_PROC(2,'문정배',33,4,66); 
EXECUTE SCORE_RANK_PROC;
​
SELECT * FROM SCORE ORDER BY RANK;

























-------------------------------------------------------
-- 선생님 VER
-- 성적처리프로그램 테이블 생성
CREATE TABLE SCORE (
    STUNUM NUMBER(4),
    NAME VARCHAR2(20) NOT NULL,
    KOR NUMBER(4) NOT NULL,
    ENG NUMBER(4) NOT NULL,
    MAT NUMBER(4) NOT NULL,
    TOT NUMBER(4),
    AVE NUMBER(5,1),
    RANK NUMBER(4)
);
-- 제약조건 등록 확인
ALTER TABLE SCORE ADD CONSTRAINT SCORE_STUNUM_PK PRIMARY KEY(STUNUM);
select * from user_cons_columns where table_name = 'SCORE';

-- 성적을 입력을 하면 총점과 평균이 자동 계산되어 입력되는 프로시저를 작성
CREATE OR REPLACE NONEDITIONABLE PROCEDURE SCORE_PROC_INPUT (
    VSTUNUM IN SCORE.STUNUM%TYPE,
    VNAME IN SCORE.NAME%TYPE,
    VKOR IN SCORE.KOR%TYPE,
    VENG IN SCORE.ENG%TYPE,
    VMAT IN SCORE.MAT%TYPE
)
IS 
    VTOT NUMBER;
    VAVE NUMBER;
BEGIN
    VTOT := VKOR + VENG + VMAT;
    VAVE := (VTOT)/3;
    INSERT INTO SCORE(STUNUM,NAME,KOR,ENG,MAT,TOT,AVE)
    VALUES (VSTUNUM,VNAME,VKOR,VENG,VMAT,VTOT,VAVE);
END;
/

EXECUTE SCORE_PROC_INPUT (1,'홍길동',99,80,85);
SELECT * FROM SCORE;

-- -- 성적을 입력을 하면 총점과 평균이 자동 계산되어 입력되는 트리거를 작성
CREATE OR REPLACE TRIGGER SCORE_TRIGGER
AFTER INSERT ON SCORE
FOR EACH ROW
DECLARE 
    VTOT NUMBER(3);
    VAVE NUMBER(5,2);
BEGIN
    VTOT := :NEW.KOR + :NEW.ENG + :NEW.MAT;
    VAVE := VTOT / 3;
END;
/

INSERT INTO SCORE (STUNUM,NAME,KOR,ENG,MAT) VALUES (2,'김희진',95,84,79);
SELECT * FROM SCORE;
INSERT INTO SCORE (STUNUM,NAME,KOR,ENG,MAT) VALUES (3,'이현수',83,89,99);

-- 김민석 트리거 처리프로그램
CREATE OR REPLACE TRIGGER SCORE_INSERT_TRG
AFTER INSERT ON SCORE
BEGIN
    UPDATE SCORE SET TOT=(KOR+ENG+MAT);
    UPDATE SCORE SET AVE=(KOR+ENG+MAT)/3;
END;
/
INSERT INTO SCORE(STUNUM,NAME,KOR,ENG,MAT) VALUES (2,'김희진',95,84,79);
SELECT * FROM SCORE;

-- 김동욱  트리거 처리프로그램
CREATE OR REPLACE TRIGGER SCORE_INSERT_TRG
    BEFORE INSERT ON SCORE
    FOR EACH ROW
BEGIN
    :NEW.TOT := :NEW.KOR + :NEW.ENG + :NEW.MAT;
    :NEW.AVE := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MAT) / 3, 1);
END;
/
INSERT INTO SCORE(STUNUM,NAME,KOR,ENG,MAT) VALUES (3,'이희진',90,80,70);
SELECT * FROM SCORE;

-- 등수를 처리하는 저장 프로시저를 생성하라.
CREATE OR REPLACE PROCEDURE SCORE_RANK_PROC
IS 
BEGIN
    UPDATE SCORE S 
    SET RANK =
    (SELECT S_RANK FROM(SELECT STUNUM, RANK()OVER(ORDER BY AVE DESC) AS S_RANK FROM SCORE) WHERE S.STUNUM=STUNUM);
END;
/
EXECUTE SCORE_RANK_PROC;
SELECT * FROM SCORE;
SELECT * FROM SCORE ORDER BY RANK ASC, KOR DESC, ENG DESC, MAT DESC;
-- 윈도우 함수를 이용해서 생성해보자

SELECT NAME, TOT, RANK() OVER(ORDER BY TOT DESC) RANK FROM SCORE ORDER BY TOT DESC; 

CREATE OR REPLACE PROCEDURE SCORE_RANK_PROC
IS 
    VSCORE_RT SCORE%ROWTYPE; 
    CURSOR C1 IS
    SELECT STUNUM, NAME, TOT,RANK() OVER(ORDER BY TOT DESC) RANK FROM SCORE ORDER BY TOT DESC; 
BEGIN
    FOR  VSCORE_RT IN C1 LOOP
        UPDATE SCORE SET RANK = VSCORE_RT.RANK WHERE STUNUM =  VSCORE_RT.STUNUM; 
    END LOOP;
    COMMIT; 
END;
/

INSERT INTO SCORE(STUNUM,NAME,KOR,ENG,MAT) VALUES (4,'구희진',100,81,71);
EXECUTE SCORE_RANK_PROC;
SELECT * FROM SCORE;
SELECT * FROM SCORE ORDER BY RANK ASC, KOR DESC, ENG DESC, MAT DESC;





 
