-- PDF_21 20쪽 예제
-- 문제1: EMP01 테이블 삭제 후 생성
DROP TABLE EMP01;
CREATE TABLE EMP01(
    NO NUMBER(4), -- PK
    NAME VARCHAR2(10) NOT NULL,
    JOB VARCHAR2(9),
    MANAGER NUMBER(4),
    HIREDATE DATE NOT NULL,
    SALARY NUMBER(7,2) NOT NULL,
    COMMISSION NUMBER(7,2) DEFAULT 0.0,
    DEPTNO NUMBER(2) NOT NULL
);
ALTER TABLE EMP01
    ADD CONSTRAINT EMP01_NO_PK PRIMARY KEY(NO);
    
SELECT * 
FROM USER_CONSTRAINTS
WHERE TABLE_NAME='EMP01';


-- 문제2: EMP01 테이블에 데이터 추가
INSERT INTO EMP01 VALUES (7369, 'SMITH', 'CLEAK', 7836, TO_DATE('1980-12-17', 'YYYY-MM-DD'), 800, NULL, 20);
INSERT INTO EMP01 VALUES (7499, 'ALLEN', 'SALESMAN', 7369, TO_DATE('1987-12-20', 'YYYY-MM-DD'), 1600, 300, 30);
INSERT INTO EMP01 VALUES (7839, 'KING', 'PRESIDENT', NULL, TO_DATE('1981-02-08', 'YYYY-MM-DD'), 5000, NULL, 10);

SELECT * FROM EMP01;


-- 문제3: MEMBERS 테이블 생성
DROP TABLE MEMBERS;
CREATE TABLE MEMBERS (
    ID VARCHAR2(20), -- PK
    NAME VARCHAR2(20) NOT NULL,
    REGNO VARCHAR2(20) NOT NULL,
    PHONE VARCHAR2(13) NOT NULL,
    ADDRESS VARCHAR2(100) NOT NULL
);
ALTER TABLE MEMBERS
    ADD CONSTRAINT MEMBER_ID_PK PRIMARY KEY(ID); 

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='MEMBERS';

INSERT INTO MEMBERS VALUES ('20201234', '전지연', '011217-1234567', '010-1234-5678', '서울시');
INSERT INTO MEMBERS VALUES ('16785678', '홍길동', '980311-2345678', '010-9876-5432', '경기도');

SELECT* FROM MEMBERS;


-- 문제4: BOOKS 테이블 생성
DROP TABLE BOOKS;
CREATE TABLE BOOKS (
    CODE NUMBER(4), -- PK
    TITLE VARCHAR2(50) NOT NULL,
    COUNT NUMBER(6) NOT NULL,
    PRICE NUMBER(10) NOT NULL,
    PUBLISH VARCHAR2(50) NOT NULL
);
ALTER TABLE BOOKS 
    ADD CONSTRAINT BOOKS_CODE_PK PRIMARY KEY(CODE);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME='BOOKS';

INSERT INTO BOOKS VALUES(3356, '자바의 정석', 12, 28000, '한빛미디어');
INSERT INTO BOOKS VALUES(7876, '라틴어 배우기', 8, 17000, '라틴미디어');

SELECT * FROM BOOKS;



-------------------------------------------------------------------------------
-- PDF 17 28쪽 예제
-- 문제1: V_CUSTOMER 테이블 만들기
DROP TABLE VCUSTOMER CASCADE CONSTRAINTS;
CREATE TABLE VCUSTOMER (
    CCODE NUMBER(5) NOT NULL, -- PK
    NAME VARCHAR2(20) NOT NULL,
    AGE NUMBER(3),
    ADDR VARCHAR2(50),
    PHONE VARCHAR2(20)
);
ALTER TABLE VCUSTOMER 
    ADD CONSTRAINT VCUSTOMER_CCODE_PK PRIMARY KEY(CCODE);

SELECT *
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME='VCUSTOMER';


-- 문제2: VIDEO 테이블 만들기 
DROP TABLE VIDEO CASCADE CONSTRAINTS;
CREATE TABLE VIDEO (
    VCODE NUMBER(5) NOT NULL, -- PK
    TITLE VARCHAR2(50) NOT NULL,
    GENRE VARCHAR2(30),
    PAY NUMBER(7) NOT NULL,
    STATE NUMBER(1),
    COMPANY VARCHAR2(50),
    MAKEDATE DATE,
    VIEWAGE NUMBER(1)
);
ALTER TABLE VIDEO 
    ADD CONSTRAINT VIDEO_VCODE_PK PRIMARY KEY(VCODE);

SELECT *
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME='VIDEO';


-- 문제3: LEND_RETURN 테이블 만들기 
DROP TABLE LENDRETURN CASCADE CONSTRAINTS;
CREATE TABLE LENDRETURN (
     LRCODE NUMBER(5) NOT NULL, -- PK
     LENDDATE DATE,
     RETURNDATE DATE,
     TOTAL NUMBER(7),
     CCODE NUMBER(5), -- FK
     VCODE NUMBER(5) -- FK
);     
ALTER TABLE LENDRETURN 
    ADD CONSTRAINT LENDRETURN_LRCODE_PK PRIMARY KEY(LRCODE);
ALTER TABLE LENDRETURN 
    ADD CONSTRAINT LENDRETURN_CCODE_FK FOREIGN KEY(CCODE) REFERENCES VCUSTOMER(CCODE);
ALTER TABLE LENDRETURN
    ADD CONSTRAINT LENDRETURN_VCODE_FK FOREIGN KEY(VCODE) REFERENCES VIDEO(VCODE);

SELECT * 
FROM USER_CONSTRAINTS 
WHERE TABLE_NAME='LENDRETURN';


