-- 문제1) employees 테이블에 등록된 총 사원의 수, 급여의 합, 급여의 평균을 변수에 대하여 출력
DECLARE 
    SUMPEOPLE NUMBER(15);
    SUMSAL NUMBER(15);
    AVGSAL NUMBER(15);
BEGIN
    SELECT COUNT(*), SUM(SALARY), AVG(SALARY)
    INTO SUMPEOPLE, SUMSAL, AVGSAL
    FROM EMPLOYEES;
    
    DBMS_OUTPUT.PUT_LINE('총 사원의 수: ' || SUMPEOPLE);
    DBMS_OUTPUT.PUT_LINE('급여의 합: ' || SUMSAL);
    DBMS_OUTPUT.PUT_LINE('급여의 평균: ' || AVGSAL);
END;
/


-- 문제2) Clara 사원의 직무, 급여, 입사일자, 커미션, 부서명을 변수에 대입하여 출력
DECLARE 
    TYPE EMP_RECORD_TYPE IS RECORD(
        JOBID EMPLOYEES.JOB_ID%TYPE,
        SALARY EMPLOYEES.SALARY%TYPE,
        HIREDATE EMPLOYEES.HIRE_DATE%TYPE,
        CMS EMPLOYEES.COMMISSION_PCT%TYPE,
        DPTID EMPLOYEES.DEPARTMENT_ID%TYPE
    ); 
    -- 레코드 타입 변수선언
    EMP_RECORD EMP_RECORD_TYPE;
BEGIN
    SELECT JOB_ID, SALARY, HIRE_DATE, COMMISSION_PCT, DEPARTMENT_ID
    INTO EMP_RECORD
    FROM EMPLOYEES 
    WHERE FIRST_NAME='Clara';
    
    DBMS_OUTPUT.PUT_LINE('사원 직무: ' || EMP_RECORD.JOBID);
    DBMS_OUTPUT.PUT_LINE('급여: ' || EMP_RECORD.SALARY);
    DBMS_OUTPUT.PUT_LINE('입사 일자: '|| EMP_RECORD.HIREDATE);
    DBMS_OUTPUT.PUT_LINE('커미션: '|| EMP_RECORD.CMS);
    DBMS_OUTPUT.PUT_LINE('부서명: '|| EMP_RECORD.DPTID);
END;
/