CREATE SEQUENCE VISIT_SEQ  -- 시퀀스이름
   START WITH 1             -- 시작을 1로 설정
   INCREMENT BY 1          -- 증가 값을 1씩 증가
   NOMAXVALUE             -- 최대 값이 무한대
   NOCACHE
   NOCYCLE;

CREATE table VISIT (
    NO         NUMBER(5,0) NOT NULL,
    WRITER     VARCHAR2(20) NOT NULL,
    MEMO    VARCHAR2(4000) NOT NULL,
    REGDATE   DATE NOT NULL
);

ALTER TABLE VISIT ADD CONSTRAINT VISIT_NO_PK PRIMARY KEY(NO);

INSERT INTO VISIT VALUES(VISIT_SEQ.NEXTVAL, 'JJY', '처음으로 메모장', SYSDATE);
SELECT * FROM VISIT;

----------------------------------------
CREATE TABLE MEMBER (
    NO NUMBER, --PK
    NAME VARCHAR2(15) NOT NULL,
    ID VARCHAR2(25) NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    SCRIPT VARCHAR2(50)
);    
ALTER TABLE MEMBER ADD CONSTRAINT MEMBER_NO_PK PRIMARY KEY(NO);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE             -- 최대 값이 무한대
NOCACHE
NOCYCLE;

INSERT INTO MEMBER VALUES (MEMBER_SEQ.NEXTVAL, '전지연', 'jiyeon', '1234', '안녕하세요 잘부탁합니다.');
SELECT * FROM MEMBER;
    
