-- 의사 테이블
DROP TABLE DOCTOR;

CREATE TABLE DOCTOR (
    DOCID   CHAR(6 CHAR), -- PK
    DOCNAME VARCHAR2(10 CHAR) NOT NULL,
    CLASSID CHAR(6 CHAR) NOT NULL -- FK
);

ALTER TABLE DOCTOR ADD CONSTRAINT DOCTOR_PK PRIMARY KEY (DOCID);
ALTER TABLE DOCTOR ADD CONSTRAINT DOCTOR_CLASSID_FK FOREIGN KEY (CLASSID) REFERENCES CLASS (CLASSID);

-- 과 테이블
DROP TABLE CLASS;

CREATE TABLE CLASS (
    CLASSID   CHAR(6 CHAR), -- PK
    C_NAME    VARCHAR2(10 CHAR) NOT NULL,
    C_PHONE   CHAR(11 CHAR) NOT NULL,
    C_ADDRESS VARCHAR2(40 CHAR) NOT NULL
);

ALTER TABLE CLASS ADD CONSTRAINT CLASS_PK PRIMARY KEY (CLASSID);

-- 환자 테이블
DROP TABLE PATIENT;

CREATE TABLE PATIENT (
    PATIID   CHAR(6), -- 환자ID, PK
    PATINAME VARCHAR2(5) NOT NULL, -- 환자이름, NN
    RESINUM  VARCHAR2(14) NOT NULL, -- 주민등록번호, UK, NN
    INSUR    CHAR(2) NOT NULL -- 보험여부, CK, NN
);

ALTER TABLE PATIENT 
    ADD CONSTRAINT PATIENT_PATIID_PK PRIMARY KEY (PATIID); 
ALTER TABLE PATIENT
    ADD CONSTRAINT PATIENT_INSUR_CK CHECK (INSUR IN ('Y', 'N'));

-- 예약 테이블
DROP TABLE RESERVATION;

CREATE TABLE RESERVATION (
    RESERVID   CHAR(6 CHAR), -- PK
    PATIID     CHAR(6 CHAR) NOT NULL, -- FK
    DOCID      CHAR(6 CHAR) NOT NULL, -- FK
    RESERVDATE DATE NOT NULL,
    STATUS     VARCHAR2(3 CHAR) NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_RESERVID_PK PRIMARY KEY (RESERVID);
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_PATIID_FK FOREIGN KEY (PATIID) REFERENCES PATIENT (PATIID) ON DELETE CASCADE;
ALTER TABLE RESERVATION ADD CONSTRAINT RESERVATION_DOCID_FK FOREIGN KEY (DOCID) REFERENCES DOCTOR (DOCID) ON DELETE CASCADE;

-- 처방 테이블
DROP TABLE PRESCRIPTION;

CREATE TABLE PRESCRIPTION (
    PREID    CHAR(6 CHAR), -- PK
    RESERVID CHAR(6 CHAR) NOT NULL, -- FK
    PATIID   CHAR(6 CHAR) NOT NULL, -- FK
    DETAIL   VARCHAR2(20 CHAR) NOT NULL
);

ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_PK PRIMARY KEY (PREID);
ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_RESERVID_FK FOREIGN KEY (RESERVID) REFERENCES RESERVATION (RESERVID) ON DELETE CASCADE;
ALTER TABLE PRESCRIPTION ADD CONSTRAINT PRESCRIPTION_PATIID_FK FOREIGN KEY (PATIID) REFERENCES PATIENT (PATIID) ON DELETE CASCADE;
