-- 자바에서 CallableStatement test
DROP TABLE EMP1;

-- 특정 컬럼만 기존 테이블에서 복사해오기 
CREATE TABLE EMP1
AS 
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID, SALARY
FROM EMPLOYEES;

SELECT * FROM EMP1;

SELECT * FROM EMP1 ORDER BY DEPARTMENT_ID;

---------------------------------------------------------

-- 프로시저 만들기 

-- 부서별로 10이면 10% 인상, 20이면 20% 인상, 나머지는 동결하는 SQL문을 프로시저로 작성
--CREATE OR REPLACE PROCEDURE EMP1_PROCEDURE (VDEPARTMENT_NO IN EMP1.DEPARTMENT_ID%TYPE )
--IS 
--BEGIN
--    UPDATE EMP1 
--    SET SALARY = DECODE(VDEPARTMENT_NO, 10, SALARY*1.1, SALARY*1.2, SALARY)
--    WHERE DEPARTMENT_ID = VDEPARTMENT_NO;
--    COMMIT;
--END;
--/

-- 부서별 번호와 인상율 입력하면 해당되는 부서만 인상률로 적용하는 SQL문을 프로시저로 작성 
CREATE OR REPLACE PROCEDURE EMP1_PROCEDURE 
    (VDEPARTMENT_NO IN EMP1.DEPARTMENT_ID%TYPE, VINCREMENT_SALARY NUMBER )
IS 
BEGIN
    UPDATE EMP1 
    SET SALARY = SALARY * VINCREMENT_SALARY
    WHERE DEPARTMENT_ID = VDEPARTMENT_NO;
    COMMIT;
END;
/
-- 프로시저 작동시켜보기
--EXECUTE EMP1_PROCEDURE(50, 2);
SELECT * FROM EMP1;

---------------------------------------------------------

-- 책값인상
-- 프로시저
CREATE OR REPLACE PROCEDURE  BOOKS_PROCEDURE(
    VID IN BOOKS.ID%TYPE, VPRICE IN BOOKS.PRICE%TYPE , VMESSAGE OUT VARCHAR2)
IS
    VBOOKS_RT BOOKS%ROWTYPE; 
BEGIN
    UPDATE BOOKS 
    SET PRICE = PRICE + VPRICE WHERE ID = VID; 
    COMMIT;
    SELECT * INTO VBOOKS_RT FROM BOOKS WHERE ID = VID; 
    VMESSAGE := VBOOKS_RT.ID||' 번호의 인상금액은 '|| VPRICE ||'이고 총 금액은'|| VBOOKS_RT.PRICE ||'입니다'; 
    DBMS_OUTPUT.PUT_LINE(VMESSAGE); 
END;
/
VARIABLE MESSAGE VARCHAR2(200);
EXECUTE BOOKS_PROCEDURE (1, 10000, :MESSAGE);

-- function 책값인상
CREATE OR REPLACE FUNCTION  BOOKS_FUNCTION(VID IN BOOKS.ID%TYPE)
    RETURN VARCHAR2
IS
    VBOOKS_RT BOOKS%ROWTYPE; 
    VMESSAGE VARCHAR2(100);
BEGIN
    SELECT * INTO VBOOKS_RT FROM BOOKS WHERE ID = VID; 
    VMESSAGE := VBOOKS_RT.ID||' 번호의 금액은'|| VBOOKS_RT.PRICE ||'입니다'; 
    RETURN VMESSAGE;
END;
/

--SELECT BOOKS_FUNCTION (2, 10000) FROM DUAL;
--EXECUTE BOOKS_FUNCTION (1, 10000);

SELECT BOOKS_FUNCTION(3) FROM DUAL;

commit;

