-- 부서 테이블 (경영, 주방, 서빙 등)
-- 직원 테이블 (직원정보, 시급)
-- 일한시간 테이블 (출근 시간, 퇴근 시간 등)
-- 지급 내역 테이블 (직원정보, 지급 내역 등)


-- 1) 부서 테이블 (경영, 주방, 서빙)----------
DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT(
    DEPID NUMBER, -- PK, 부서ID
    DEPNAME VARCHAR2(20) NOT NULL -- 부서 이름 
);
ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_DEPID_PK PRIMARY KEY(DEPID);

DROP SEQUENCE DEPARTMENT_SEQ;
CREATE SEQUENCE DEPARTMENT_SEQ
START WITH 1
INCREMENT BY 1;

--INSERT INTO DEPARTMENT VALUES (DEPARTMENT_SEQ.NEXTVAL, ?);


-- 2) 직원 테이블(직원정보, 시급)-------------------
DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE(
    EMPID NUMBER, -- PK, 직원ID
    NAME VARCHAR2(20) NOT NULL,-- 직원 이름
    RAGE NUMBER NOT NULL, -- 시급
    FKDEPID NUMBER NOT NULL -- FK, 부서ID
);    
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_EMPID_PK PRIMARY KEY(EMPID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_DEPARTMENT_DEPID_FK
    FOREIGN KEY(FKDEPID) REFERENCES DEPARTMENT(DEPID) ON DELETE CASCADE;

DROP SEQUENCE EMPLOYEE_SEQ;
CREATE SEQUENCE EMPLOYEE_SEQ
START WITH 1
INCREMENT BY 1;

--INSERT INTO EMPLOYEE VALUES (EMPLOYEE_SEQ.NEXTVAL, ?, ?, ?);


-- 3) 일한시간 테이블 (출근 시간, 퇴근 시간)-----------------------------
DROP TABLE WORKHOUR;
CREATE TABLE WORKHOUR(
    WHID NUMBER, --PK, 근무시간ID 
    WDATE DATE  NOT NULL, -- 근무 날짜
    CHECKIN TIMESTAMP NOT NULL, --  출근 시간 
    CHECKOUT TIMESTAMP NOT NULL, -- 퇴근 시간
    WH_EMPID NUMBER NOT NULL, -- FK, 직원ID
    HOURS NUMBER(2, 1) NOT NULL, -- 퇴근시간-출근시간(일한시간)
    AMOUNT NUMBER NOT NULL -- 임금(시급*일한시간)
);
ALTER TABLE WORKHOUR ADD CONSTRAINT WORKHOUR_WHID_PK PRIMARY KEY(WHID);
ALTER TABLE WORKHOUR ADD CONSTRAINT WORKHOUR_EMPLOYEE_EMPID_FK
    FOREIGN KEY(WH_EMPID) REFERENCES EMPLOYEE(EMPID) ON DELETE CASCADE;

DROP SEQUENCE WORKHOUR_SEQ;
CREATE SEQUENCE WORKHOUR_SEQ
START WITH 1
INCREMENT BY 1;

--INSERT INTO WORKHOUR VALUES (WORKHOUR_SEQ.NEXTVAL, ?, ?, ?);


-- 4) 지급 내역 테이블 (직원정보, 지급 내역 등)
DROP TABLE HISTORY;
CREATE TABLE HISTORY (
    HISTORYID NUMBER, -- PK, 지급 기록 ID
    H_EMPID NUMBER NOT NULL,  -- FK, 직원 ID
    H_WHID NUMBER NOT NULL,  -- FK, 근무시간 ID
    PAY_DATE DATE NOT NULL,   -- 지급 날짜
    AMOUNT NUMBER NOT NULL,   -- 지급 금액
    METHOD VARCHAR2(20),  -- 지급 방식 (현금, 계좌 이체 등)
    STATUS VARCHAR2(10)  -- 지급 상태 (완료, 대기 등)
);
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_HISTORYID_PK PRIMARY KEY (HISTORYID);
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_EMPLOYEE_EMPID_FK
    FOREIGN KEY (H_EMPID) REFERENCES EMPLOYEE(EMPID) ON DELETE CASCADE;
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_WORKHOUR_WHID_FK 
    FOREIGN KEY(H_WHID) REFERENCES WORKHOUR(WHID) ON DELETE CASCADE;
ALTER TABLE HISTORY ADD CONSTRAINT HISTORY_STATUS_CHECK CHECK (STATUS IN ('완료', '대기'));

DROP SEQUENCE HISTORY_SEQ;
CREATE SEQUENCE HISTORY_SEQ
START WITH 1
INCREMENT BY 1;

-- INSERT INTO PAY_HISTORY VALUES (PAY_HISTORY_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?);


COMMIT;

CREATE OR REPLACE TRIGGER WORKHOUR_TRIGGER
BEFORE INSERT OR UPDATE ON WORKHOUR
FOR EACH ROW
BEGIN
    -- 출근 시간과 퇴근 시간이 모두 존재하는 경우에만 계산
    IF :NEW.CHECKIN IS NOT NULL AND :NEW.CHECKOUT IS NOT NULL THEN
        -- 일한 시간(HOURS) 계산: (퇴근 시간 - 출근 시간) * 24
        -- CHECKIN과 CHECKOUT의 차이는 날짜 간의 간격이므로, 이 값을 정확히 계산하려면 TO_NUMBER로 변환
        :NEW.HOURS := ROUND((TO_NUMBER(:NEW.CHECKOUT - :NEW.CHECKIN) * 24), 1);

        -- 임금(AMOUNT) 계산: 직원의 시급(RAGE) * 일한 시간(HOURS)
        SELECT RAGE 
        INTO :NEW.AMOUNT 
        FROM EMPLOYEE 
        WHERE EMPID = :NEW.WH_EMPID;

        :NEW.AMOUNT := :NEW.AMOUNT * :NEW.HOURS;
    END IF;
END;
/

COMMIT;
 
    
    
    
--CREATE OR REPLACE VIEW PAY_VIEW AS
--SELECT 
--    W.WH_EMPID AS 직원ID,
--    E.NAME AS 직원명,
--    W.WDATE AS 근무일자,
--    ROUND((W.CHECKOUT - W.CHECKIN) * 24, 1) AS 일한시간,
--    ROUND((W.CHECKOUT - W.CHECKIN) * 24, 1) * E.RAGE AS 임금
--FROM WORKHOUR W
--JOIN EMPLOYEE E ON W.WH_EMPID = E.EMPID;

    
