-- STUDENTS 테이블 정의
DROP TABLE STUDENTS;
CREATE TABLE STUDENTS (
    ID NUMBER(4),-- PK
    NAME VARCHAR2(10) NOT NULL,
    KOR NUMBER(3)NOT NULL,
    ENG NUMBER(3) NOT NULL,
    MATH NUMBER(3) NOT NULL,
    SUM NUMBER(3),
    AVG NUMBER(3, 1),
    RANK NUMBER(4)
);    
ALTER TABLE STUDENTS ADD CONSTRAINT ID_PK PRIMARY KEY(ID); 

-- 시퀀스 정의
DROP SEQUENCE STUDENTS_ID_SEQ;

CREATE SEQUENCE STUDENTS_ID_SEQ
START WITH 1
INCREMENT BY 1;

DESC STUDENTS;
  
-- MVC패턴 할때는 값을 INSERT 하는 부분을 뺌   
--INSERT INTO STUDENTS (ID, NAME , KOR, ENG, MATH) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '전지연', 72, 84, 93);
--INSERT INTO STUDENTS (ID, NAME , KOR, ENG, MATH) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '홍길동', 77, 55, 43);
--INSERT INTO STUDENTS (ID, NAME , KOR, ENG, MATH) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '이몽룡', 99, 43, 13);
--INSERT INTO STUDENTS (ID, NAME , KOR, ENG, MATH) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '성춘향', 85, 77, 81);
--INSERT INTO STUDENTS (ID, NAME , KOR, ENG, MATH) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '임꺽정', 14, 24, 52);  
  
COMMIT;

SELECT * FROM STUDENTS;




-- 성적을 입력하면 총점과 평균이 자동 계산되어 입력되는 트리거
CREATE OR REPLACE TRIGGER STUDENTS_TRIGGER
BEFORE INSERT ON STUDENTS
FOR EACH ROW
BEGIN
    :NEW.SUM := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MATH) / 3, 1);
END;
/

-- 성적을 수정하면 총점과 평균이 같이 변하는 트리거
CREATE OR REPLACE TRIGGER STUDENTS_TRIGGER2
BEFORE UPDATE ON STUDENTS
FOR EACH ROW
BEGIN
    :NEW.SUM := :NEW.KOR + :NEW.ENG + :NEW.MATH;
    :NEW.AVG := ROUND((:NEW.KOR + :NEW.ENG + :NEW.MATH) / 3, 1);
END;
/

-- 등수를 처리하는 저장 프로시저 생성
CREATE OR REPLACE PROCEDURE STUDENTS_RANK_PROC
IS 
    VSTUDENTS_RT STUDENTS%ROWTYPE; 
    CURSOR C1 IS
    SELECT ID, NAME, SUM, RANK() OVER(ORDER BY SUM DESC) RANK FROM STUDENTS ORDER BY SUM DESC; 
BEGIN
    FOR  VSTUDENTS_RT IN C1 LOOP
        UPDATE STUDENTS SET RANK = VSTUDENTS_RT.RANK WHERE ID =  VSTUDENTS_RT.ID; 
        COMMIT;
    END LOOP;
    COMMIT;
END;
/

EXECUTE STUDENTS_RANK_PROC;
commit;




