DROP TABLE STUDENTS;
-- STUDENTS 테이블 만들기
CREATE TABLE STUDENTS (
    ID NUMBER(4),
    NAME VARCHAR2(10),
    BIRTH DATE,
    ADDR VARCHAR2(30)
);
-- ID에 PK 제약조건 추가
ALTER TABLE STUDENTS ADD CONSTRAINT STUDENTS_ID_PK PRIMARY KEY(ID);

DROP SEQUENCE STUDENTS_ID_SEQ;
-- ID에 시퀀스 적용하기
CREATE SEQUENCE STUDENTS_ID_SEQ
START WITH 1
INCREMENT BY 1;

-- 확인하기 
DESC STUDENTS;

SELECT * FROM USER_CONS_COLUMNS WHERE TABLE_NAME = 'STUDENTS';

INSERT INTO STUDENTS (ID, NAME , BIRTH, ADDR) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '전지연', '2001-12-17', '서울시 서초구');
INSERT INTO STUDENTS (ID, NAME , BIRTH, ADDR) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '홍길동', '2004-03-11', '경기도 동두천시');
INSERT INTO STUDENTS (ID, NAME , BIRTH, ADDR) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '이몽룡', '1999-07-19', '강원도 원주시');
INSERT INTO STUDENTS (ID, NAME , BIRTH, ADDR) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '성춘향', '2006-05-05', '충청북도 청주시');
INSERT INTO STUDENTS (ID, NAME , BIRTH, ADDR) VALUES (STUDENTS_ID_SEQ.NEXTVAL, '임꺽정', '2001-07-16', '경기도 화성시');

SELECT MAX(ID) FROM STUDENTS;

COMMIT;

SELECT * FROM STUDENTS;