-- 순위함수 RANK(), DENSE_RANK(), ROWNUM
-- ROWNUM 구하는 순위(공동 순위는 없다; 게시판, 장바구니 .. )
DROP TABLE EMP01;
DROP TABLE EMP02;

CREATE TABLE EMP02
AS 
SELECT * FROM EMPLOYEES WHERE 1=1;
SELECT * FROM EMP02;

SELECT ROWNUM, FIRST_NAME, SALARY 
FROM EMPLOYEES 
ORDER BY SALARY DESC;

SELECT ROWNUM, FIRST_NAME, SALARY 
FROM EMPLOYEES;

SELECT ROWNUM, FIRST_NAME, SALARY  
FROM (
SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES 
ORDER BY SALARY DESC);

-- 공동순위 구하는 방법(RANK, DANSE_RANK)
SELECT RANK() OVER (ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY 
FROM EMPLOYEES ORDER BY SALARY DESC; 

SELECT RANK() OVER (ORDER BY SALARY DESC) AS RANK, FIRST_NAME, SALARY 
FROM (
SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES 
ORDER BY SALARY DESC
) ORDER BY SALARY DESC; 

SELECT ROWNUM, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSE_RANK, FIRST_NAME, SALARY 
FROM EMPLOYEES ORDER BY SALARY DESC;

SELECT ROWNUM, DENSE_RANK() OVER (ORDER BY SALARY DESC) AS DENSE_RANK, FIRST_NAME, SALARY 
FROM (
SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES 
ORDER BY SALARY DESC
)
ORDER BY SALARY DESC;

SELECT ROWNUM, RANK() OVER (ORDER BY SALARY DESC) AS RANK, DENSE_RANK() FIRST_NAME, SALARY 
FROM (
SELECT FIRST_NAME, SALARY 
FROM EMPLOYEES 
ORDER BY SALARY DESC
)
ORDER BY SALARY DESC;


-- 중복 순위 없애기 
SELECT RANK() OVER(ORDER BY SALARY DESC, COMMISSION_PCT DESC) AS RANK , 
FIRST_NAME, SALARY, COMMISSION_PCT  
FROM EMPLOYEES ORDER BY SALARY DESC;

-- 부서별 순위 구하기
SELECT DEPARTMENT_ID, 
RANK() OVER(PARTITION BY DEPARTMENT_ID ORDER BY SALARY DESC, COMMISSION_PCT DESC) AS RANK , 
FIRST_NAME, SALARY, COMMISSION_PCT  
FROM EMPLOYEES ORDER BY DEPARTMENT_ID, SALARY DESC, COMMISSION_PCT DESC;



-- ROWNUM 규칙 중요(조심)
SELECT * FROM EMPLOYEES 
WHERE ROWNUM BETWEEN 11 AND 20;
SELECT ROWNUM, E.*
FROM EMPLOYEES E;















-- 2페이지 정보를 구해라 
-- 순위 구하는 방법 (비추)
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID FROM (
SELECT ROWNUM AS RNUM, E.* 
FROM EMPLOYEES E)
WHERE RNUM BETWEEN 11 AND 20;

-- 순위 구하는 방법 (강추): 속도가 빠름 
SELECT RNUM, FIRST_NAME, SALARY, DEPARTMENT_ID FROM (
SELECT ROWNUM AS RNUM, E.* 
FROM EMPLOYEES E
WHERE ROWNUM <= 110)
WHERE RNUM >= 100;
