-- STORED PROCEDURE
-- EMPLOYEES에서 사용자 이름을 패턴으로 검색한뒤 해당되는 사용자정보(사원번호,이름,급여)를 보여주시오. 
SELECT * FROM EMPLOYEES WHERE upper(FIRST_NAME) LIKE upper('%p%');
SELECT  DBMS_RANDOM.STRING('U',1) FROM DUAL;

CREATE OR REPLACE PROCEDURE EMP_PROC
IS
    -- 1문자 변수 선언
    VWORD VARCHAR2(1);
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE; 
    CURSOR CURSOR_NAME(VNAME VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE upper(FIRST_NAME) LIKE upper('%'||VNAME||'%');
BEGIN
    -- 임의의 문자를 생성시킨다. 
    VWORD := DBMS_RANDOM.STRING('U',1);
    
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME || '/'||VEMP_ROWTYPE.SALARY); 
    END LOOP; 
END;
/


EXECUTE emp_proc;
//
SELECT * FROM USER_TABLES;
SELECT * FROM USER_CONSTRAINTS;
SELECT * FROM USER_CONS_COLUMNS;
SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;
SELECT * FROM USER_VIEWS;
SELECT * FROM USER_SOURCE;
SELECT * FROM USER_SEQUENCES;

-- 
create or replace NONEDITIONABLE PROCEDURE EMP_PROC2(VWORD IN VARCHAR2)
IS
    VEMP_ROWTYPE EMPLOYEES%ROWTYPE; 
    CURSOR CURSOR_NAME(VWORD VARCHAR2)
    IS
    SELECT * FROM EMPLOYEES WHERE upper(FIRST_NAME) LIKE upper('%'||VWORD||'%');
BEGIN
    FOR VEMP_ROWTYPE IN CURSOR_NAME(VWORD) LOOP
        DBMS_OUTPUT.PUT_LINE(VEMP_ROWTYPE.FIRST_NAME || '/'||VEMP_ROWTYPE.SALARY); 
    END LOOP; 
END;
/
EXECUTE EMP_PROC2('K'); 



-- EMP01 테이블 복사
SELECT * 
FROM USER_TABLES
WHERE TABLE_NAME='EMP01';

DROP TABLE EMP01;

CREATE TABLE EMP01
AS 
SELECT * FROM EMPLOYEES
WHERE 1=1;

SELECT * FROM EMP01;
-- 부서별로 월급을 인상하는 프로그램이다. 
-- 10번 부서 10% 인상, 20번 부서 20% 인상, 나머지는 동결
CREATE OR REPLACE PROCEDURE EMP01_PROC(VDEPTNO IN EMPLOYEES.DEPARTMENT_ID%TYPE)
IS
    IF VDEPTNO = 10 THEN
        UPDATE EMP01 SET SALARY = SALARY * 1.1 WHERE DEPARTMENT_ID = VDEPTNO;
        DBMS_OUTPUT.PUT_LINE(VDEPTNO || '부서는 전원 10% 인상했습니다.');
    ELSIF VDEPTNO = 20 THEN
        UPDATE EMP01 SET SALARY = SALARY * 1.2 WHERE DEPARTMENT_ID = VDEPTNO;
        DBMS_OUTPUT.PUT_LINE(VDEPTNO || '부서는 전원 20% 인상했습니다.');
    ELSE
        DBMS_OUTPUT.PUT_LINE(VDEPTNO || '부서는 전원 동결입니다.');
    END IF;
BEGIN
END;
/