-- INSERT INTO 테이블명(컬럼명 ... ) VALUES (컬럼값 ... )
-- 테이블 생성
CREATE TABLE IT(
    NO1 NUMBER,
    NO2 NUMBER,
    NO3 NUMBER
);

--컬럼 확인 
DESC IT;

-- INSERT 하기
INSERT INTO IT VALUES(1, 2, 3);
INSERT INTO IT VALUES(1, 2, NULL);
INSERT INTO IT(NO1, NO2) VALUES(11, 22);
INSERT INTO IT(NO1, NO2) VALUES(11, '문자');
INSERT INTO IT(NO1, NO2) VALUES(111);
INSERT INTO IT(NO1, NO2) VALUES(111, 222,333);
INSERT INTO IT(NO1, NO2) VALUES(1111, 2222);
INSERT INTO IT VALUES(1111, NULL, 3333);


-- INSERT 후 전체 테이블 확인
SELECT * FROM IT;
-- 테이블 망쳤을 때 초기화 용도
DROP TABLE IT;

-- NO3 NOT NULL 제약조건 걸기
ALTER TABLE IT MODIFY NO3 NUMBER NOT NULL;
DELETE FROM IT WHERE NO3 IS NULL;

-- DEPT 테이블 생성
CREATE TABLE DEPT
AS 
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS;

-- DEPT 테이블 확인
SELECT *
FROM DEPT;

-- 구조는 놔두고 내용만 지우기: DELETE 
DELETE FROM DEPT;
-- DELETE는 (구조는 남아있기 때문에) 롤백 가능
ROLLBACK;
-- 구조와 내용 모두 지우기: TRUNCATE
TRUNCATE TABLE DEPT;
-- TRUNCATE는 구조도 잘리기 때문에 롤백 불가능 
ROLLBACK;

INSERT INTO DEPT
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, LOCATION_ID
FROM DEPARTMENTS;


