ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER JYSITE CASCADE;
CREATE USER JYSITE IDENTIFIED BY 123456
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO JYSITE;    