ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER TOURDB CASCADE;
CREATE USER TOURDB IDENTIFIED BY 123456
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO TOURDB;    