ALTER SESSION SET "_ORACLE_SCRIPT"=true; -- 시스템에서 만들기 위한 명령어 
DROP USER PDB CASCADE; -- 기존 사용자 삭제
CREATE USER PARTTIMEDB IDENTIFIED BY 123456 -- 사용자 이름:SUBJECT, 비밀번호 : 1234
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP; -- 임시로 저장장소
GRANT connect, resource, dba TO PARTTIMEDB; -- 권한 부여