ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
DROP USER JYWEB CASCADE;
CREATE USER JYWEB IDENTIFIED BY 123456
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE, DBA TO JYWEB;    