-- jysite DB
-- user 테이블
--아이디
--비밀번호
--이름
--생년월일
--성별
--이메일
--휴대전화
--나라
--우편번호
--주소1
--주소2
DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    ID VARCHAR2(20),
    PW VARCHAR2(20) NOT NULL,
    NAME VARCHAR2(10) NOT NULL,
    BIRTH DATE NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    ZIP VARCHAR2(10) NOT NULL,
    ADDR1 VARCHAR2(40) NOT NULL,
    ADDR2 VARCHAR2(40) NOT NULL
);
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY(ID);

DROP TABLE ZIP;
CREATE TABLE ZIP (
    SEQ    NUMBER(10) NOT NULL,
    ZIPCODE VARCHAR2(50),
    SIDO    VARCHAR2(50),
    GUGUN   VARCHAR2(50),
    DONG    VARCHAR2(50),
    BUNJI   VARCHAR2(100)
);
ALTER TABLE ZIP ADD CONSTRAINT ZIP_SEQ_PK PRIMARY KEY ( SEQ);


SELECT * FROM STUDENT;
SELECT * FROM ZIP;
-------------------------

-- 답변형 게시판
drop table board;
CREATE TABLE  BOARD (
    NUM         NUMBER(7,0) NOT NULL , 
    WRITER      VARCHAR2(12) NOT NULL, 
    EMAIL       VARCHAR2(30) NOT NULL, 
    SUBJECT     VARCHAR2(50) NOT NULL, 
    PASS        VARCHAR2(10) NOT NULL , 
    READCOUNT   NUMBER(5,0) DEFAULT 0, 
    REF       NUMBER(5,0) DEFAULT 0, 
    STEP        NUMBER(3,0) DEFAULT 0 , 
    DEPTH     NUMBER(3,0) DEFAULT 0, 
    REGDATE     TIMESTAMP (6) DEFAULT SYSDATE, 
    CONTENT   VARCHAR2(4000) NOT NULL , 
    IP          VARCHAR2(20) NOT NULL 
   );  
 ALTER TABLE BOARD ADD CONSTRAINT BOARD_NUM_PK PRIMARY KEY (NUM);
 
 drop sequence board_seq;
 CREATE SEQUENCE BOARD_SEQ
 START WITH 1
 INCREMENT BY 1
 NOMAXVALUE
 NOCACHE
 NOCYCLE;
 
 select * from board;